### ISSUE TITLE
Jekyll is once again emitting a putrescent stench

### ISSUE THREAD

**Issue by rossabaker** [typelevel/case-insensitive#109]
```
Run gem install bundler
Successfully installed bundler-2.2.5
Parsing documentation for bundler-2.2.5
Installing ri documentation for bundler-2.2.5
Done installing documentation for bundler after 5 seconds
1 gem installed
Fetching gem metadata from http://rubygems.org/.........
listen-3.2.1 requires ruby version >= 2.2.7, ~> 2.2, which is incompatible with
the current version, ruby 3.0.0p0
Error: Process completed with exit code 5.
```

Builds that worked last week are now all failing like that.

**Comment by guruscott** [comment]
Does anyone know a web framework thats actually good - that doesnt break all the time? #unreliable

**Comment by rossabaker** [comment]
Jekyll is good, but it takes Ruby knowledge to keep shelf stable that shouldn't be necessary on a non-Ruby project.  Where stability is the primary requirement, I like the single-binary approach of Hugo.  For a Scala project like this, I recommend paradox, which is managed through SBT.
