### ISSUE TITLE
Arbitrary[CIString] is extremely slow in v1.4.0

### ISSUE THREAD

**Issue by bpholt** [typelevel/case-insensitive#442]
The `Arbitrary[CIString]` instance published in case-insensitive-testkit `v1.4.0` is extremely slow. Running the `MonoidTests[Map[CIString, String]].monoid` tests from cats-laws takes 4–5 minutes on my computer with `v1.4.0`. This was fixed in 7f27b01, and using the snapshot published when that was merged improves the runtime on those law tests to 3–4 seconds.

Could we publish a `v1.4.1` with that change (and possibly everything up to the Scala Native 0.5 update in #431)? I think it would be tagged on either 713ccf0 (because that's the merge commit for 7f27b01) or 12875f1 (because that's the merge immediately preceding #431).

**Comment by bpholt** [comment]
Here's an example of code that could benefit from a `v1.4.1`: https://github.com/typelevel/natchez/pull/1071

**Comment by rossabaker** [comment]
https://github.com/typelevel/case-insensitive/releases/tag/v1.4.1

**Comment by bpholt** [comment]
Thanks @rossabaker!

**Comment by bpholt** [comment]
@rossabaker it looks like the build failed for that release… 😢

**Comment by rossabaker** [comment]
Should be fixed as 1.4.2.
